server:
  port: 8085
#  servlet:
#    context-path: /student

spring:
  data:
    mongodb:

      uri: mongodb://admin:123456@localhost:27017/student_db?authSource=admin&authMechanism=SCRAM-SHA-1
#      uri: mongodb://admin:123456@mongodb:27017/student_db?authSource=admin&authMechanism=SCRAM-SHA-1
#      uri: mongodb://admin:123456@172.30.120.15:27017/student_db?authSource=admin&authMechanism=SCRAM-SHA-1


#nhom:
#  hoc:
#    service:
#      url: "http://172.30.120.20:8000/nhomdkhp/nhomhoc/"
#course:
#  service:
#    url: "http://172.30.120.20:8000/course/api/courses/"
