server:
  port: 8084
  servlet:
    context-path: /nhomdkhp

spring:
  data:
    mongodb:
#      uri: mongodb://admin:123456@mongodb:27017/student_db?authSource=admin&authMechanism=SCRAM-SHA-1
      uri: mongodb://admin:123456@localhost:27017/student_db?authSource=admin&authMechanism=SCRAM-SHA-1
#      uri: mongodb://admin:123456@172.30.120.15:27017/student_db?authSource=admin&authMechanism=SCRAM-SHA-1


#external:
#  service:
#    hoc-ky-url: http://localhost:8000/khht/api/hocki/{mahocki}
#    course-url: http://localhost:8000/course/api/courses/{maHocPhan}
